version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: keeper
    main: ./cmd/keeper
    binary: keeper
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v2
    env:
      - CGO_ENABLED=0
    ldflags: -s -w
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: amd64

archives:
  - formats:
    - binary
    id: keeper

dockers:
  - id: keeper
    goos: linux
    goarch: amd64
    goamd64: v2
    build_flag_templates:
      - "--build-arg=VERSION={{.Tag}}"
    image_templates:
      - "ghcr.io/bruno-chavez/keeper:{{ .Tag }}"
      - "ghcr.io/bruno-chavez/keeper:v{{ .Major }}"
      - "ghcr.io/bruno-chavez/keeper:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/bruno-chavez/keeper:latest"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
