name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.46.2
          ./bin/golangci-lint run

      - name: Test
        run: |
          wget -o -q https://github.com/mfridman/tparse/releases/download/v0.10.3/tparse_linux_x86_64 -O tparse
          go test ./... -json -cover | ./tparse

      - name: Build CLI Binary
        run: |
          cd cmd/cli-tool
          go build

      - name: Build REST API Binary
        run: |
          cd cmd/rest-server
          go build

      - name: Build Docker Image
        run: docker build .
